### PR TITLE
Add Prosilica classes for both HDF5 and TIFF plugins

### PR DESCRIPTION
**Pull request by mrakitin**
Also, instantiate and configure `cam6`.

Based on https://github.com/NSLS-II-HXN/flyer_profile/blob/master/startup/10-detectors.py.

### Issues observed:
- https://github.com/NSLS-II-TES/profile_collection/issues/18

### CODE REVIEW

**Review by jklynch — APPROVED** [review]
Would it make sense to put all of these classes into nslsii sometime in the future?

Otherwise this all looks good to me.

**Review by dmgav — APPROVED** [review]

**Comment by dmgav** [comment]
@mrakitin Should we merge this? I was planning to do some work on TES today.

**Comment by mrakitin** [comment]
The classes are ~ready, but the camera produces differently shaped arrays, such as `[<num_frames>, <y>, <x>, <3 RGB channels>]`, so it needs a separate handler to read the data, and probably I'll have to change the spec from `AD_HDF5` to the one which would be associated with the handler.

**Comment by mrakitin** [comment]
@dmgav, @jklynch, @gwbischof, ready for another round of your review. I added some tools for users to be more efficient at TES.

**Comment by mrakitin** [comment]
This code was used during the beamtime in January and proved to be working OK. Going to self-merge.

**Pull request merged**
