### PR TITLE
xspress3 community IOC

### PR DESCRIPTION
**Pull request by mrakitin**
The beamline runs off that branch.

### CODE REVIEW

**Comment by mrakitin** [comment]
https://github.com/NSLS-II-TES/profile_collection/pull/37/commits/22684eef87ba93edb862562d4fc35fd82c44d074 is a fix to make it work at the beamline.

**Comment by dmgav** [comment]
Please, remove the last commit. The code looks as if it is working, but in reality it does not. The data is saved incorrectly and are unreadable. The original code (without the last commit) works correctly on the beamline. It is not clear why it does not pass CI. It could have something to do with versions of installed packages and needs further investigation.

**Comment by dmgav** [comment]
The profile is passing the CI tests if `nslsii` package is updated to the latest version: https://github.com/NSLS-II-TES/profile_collection/tree/test
May be the tests should be switched to the latest environment.

**Comment by dmgav** [comment]
Closing in favor of https://github.com/NSLS-II-TES/profile_collection/pull/38

**Pull request closed without merging**
