### PR TITLE
Compatibility with collection-2021-1.0

### PR DESCRIPTION
**Pull request by mrakitin**
Uses https://github.com/NSLS-II/profile-collection-ci/blob/main/collection-2021-1.0.yml for the Azure Pipelines configuration.

Closes #7.

### CODE REVIEW

**Comment by mrakitin** [comment]
cc @jmagithub

**Review by jklynch — APPROVED** [review]
What does it mean to have more than one `- template:`?

**Comment by mrakitin** [comment]
@jklynch, the 2 templates are for 2 different configurations:
image

https://github.com/NSLS-II/profile-collection-ci/tree/main lists those 2 configurations. Basically, we are testing against `collection-2021-1.0` (currently deployed on the floor), and `collection-2021-1.2` (to be deployed).

**Review by AbbyGi — APPROVED** [review]
Looks good to me.

**Pull request merged**
