### PR TITLE
MNT: make handler forgiving of corrupted files

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by lcdesilva** [comment]
Do we understand the source of corruption?

**Comment by tacaswell** [comment]
If it is also corrupted on the IOC, then that is a question for you, if it is OK on the IOC then that is a question for Matt.

**Comment by lcdesilva** [comment]
Ok. I can acquire data just from the IOC and test it. That means there is no stage movement and triggering. Just a simple snapshot for a given exposure. I would then manually load this file via BlueSky and analyze. Can I use the functions already in 23-xspress3.py to test corruption? If so please let me know what commands to run at BSUI command prompt. That way I can produce something we can easily compare.

**Comment by danielballan** [comment]
Closing as hopelessly stale.

**Pull request closed without merging**
